
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: GraduationAnselme_development


test:
  <<: *default
  database: GraduationAnselme_test


production:
  <<: *default
  database: GraduationAnselme_production
  username: GraduationAnselme
  password: <%= ENV['GRADUATIONANSELME_DATABASE_PASSWORD'] %>
